run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters-settings:
  gofumpt:
    extra-rules: true
  misspell:
    locale: US
  lll:
    line-length: 140
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - opinionated
      - experimental
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - importShadow
      - unnamedResult
  revive:
    severity: warning

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - gofumpt
    - revive
    - misspell
    - errcheck
    - ineffassign
    - goimports
    - gocritic
    - gocyclo
    - gochecknoinits
    - goconst
    - lll
    - nakedret
    - noctx
    - rowserrcheck
    - typecheck
    - unparam
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
