app = "strive-api"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 100

  [[http_service.checks]]
    name = "health"
    type = "http"
    interval = "30s"
    timeout = "3s"
    grace_period = "5s"
    method = "GET"
    path = "/health"


