services:
  - type: web
    name: strive-api
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FORMAT
        value: json
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL_MODE
        value: require
      - key: JWT_SECRET
        sync: false

