basePath: /
definitions:
  http.AuthResponse:
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
      expires_in:
        example: 900
        type: integer
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
      token_type:
        example: Bearer
        type: string
    type: object
  http.DetailedHealthResponse:
    properties:
      services:
        additionalProperties:
          $ref: '#/definitions/http.ServiceInfo'
        type: object
      status:
        type: string
      timestamp:
        type: string
    type: object
  http.ErrorResponse:
    properties:
      error:
        properties:
          code:
            example: VALIDATION_ERROR
            type: string
          message:
            example: Invalid input data
            type: string
        type: object
    type: object
  http.LoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
    required:
    - email
    - password
    type: object
  http.RefreshRequest:
    properties:
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    required:
    - refresh_token
    type: object
  http.RegisterRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  http.ServiceInfo:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
host: strive-api-zjtl.onrender.com
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for workout diary with user authentication
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Strive API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT tokens
      parameters:
      - description: User login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/http.AuthResponse'
        "400":
          description: Invalid request data
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: Login user
      tags:
      - authentication
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh access token using refresh token
      parameters:
      - description: Refresh token data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Token refreshed successfully
          schema:
            $ref: '#/definitions/http.AuthResponse'
        "400":
          description: Invalid request data
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "401":
          description: Invalid refresh token
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: Refresh access token
      tags:
      - authentication
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Create a new user account with email and password
      parameters:
      - description: User registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request data
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: Register a new user
      tags:
      - authentication
  /health:
    get:
      consumes:
      - application/json
      description: Check if the API is running
      produces:
      - application/json
      responses:
        "200":
          description: API is healthy
          schema:
            $ref: '#/definitions/http.DetailedHealthResponse'
      summary: Health check
      tags:
      - system
  /health/db:
    get:
      consumes:
      - application/json
      description: Check if the database is accessible
      produces:
      - application/json
      responses:
        "200":
          description: Database is healthy
          schema:
            $ref: '#/definitions/http.DetailedHealthResponse'
        "503":
          description: Database is unhealthy
          schema:
            $ref: '#/definitions/http.DetailedHealthResponse'
      summary: Database health check
      tags:
      - system
  /health/detailed:
    get:
      consumes:
      - application/json
      description: Check all system components
      produces:
      - application/json
      responses:
        "200":
          description: All systems healthy
          schema:
            $ref: '#/definitions/http.DetailedHealthResponse'
        "503":
          description: Some systems unhealthy
          schema:
            $ref: '#/definitions/http.DetailedHealthResponse'
      summary: Detailed health check
      tags:
      - system
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
